pipeline {
  agent { docker { image 'mcr.microsoft.com/playwright:v1.21.0-focal' } }

 stages {
      stage('e2e-tests') {
         steps {
            sh 'npm install'
            sh 'npm run test search.spec.ts'
         }
      }
   }
}

//   stages {
//     stage('Install Playwright') {
//       steps {
//         echo 'Install Playwright'
//         sh '''
//         npm -i -D @playwright/test
//         npx playwright install
//         '''
//         }
//     }
//     stage('Help Playwright') {
//         steps {
//             echo 'Help Playwright'
//             sh 'npx playwright test -- help'
//         }
//     } 
//     stage('Run Playwright Tests') {
//       steps {
//         echo 'Run Playwright Tests'
//         sh '''
//         npm playwright test --list
//         npx playwright test 
//         '''
//       }
//     }
//   }
// }

